"""update cpf (nullable),optional

Revision ID: 5b8a849fe51b
Revises: b8498e564285
Create Date: 2026-05-13 22:16:21.648478

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8a849fe51b'
down_revision = 'b8498e564285'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('cpf', sa.String(length=14), nullable=True))
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint('uq_customers_company_cpf', 'customers', ['company_id', 'cpf'])
    op.create_unique_constraint(None, 'customers', ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_constraint('uq_customers_company_cpf', 'customers', type_='unique')
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('customers', 'cpf')
    # ### end Alembic commands ###

